### ISSUE TITLE
启动时导入插件报错

### ISSUE THREAD

**Issue by Old-Second** [Refound-445/nonebot-plugin-nailongremove#24]
```
[ERROR] nonebot | Failed to import "nonebot_plugin_nailongremove"
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/root/guoba/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/guoba/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/guoba/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/guoba/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/guoba/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 182, in load_plugin
    raise RuntimeError(
RuntimeError: Module nonebot_plugin_nailongremove is not loaded as a plugin! Make sure not to import it before loading.
```

**Comment by lgc2333** [comment]
你是否有自定义bot.py？

**Comment by Old-Second** [comment]
> 你是否有自定义bot.py？

没有，今天更新最新版之后出现的问题。之前导入没有报错（但功能也不能正常触发，很多次才会触发一次）

**Comment by Champion31415926** [comment]
i have the same quetion

**Comment by Champion31415926** [comment]
how do you solve the problem  @Old-Second

**Comment by Refound-445** [comment]
I suggest that reinstalling this plugin can solve all the issues.

**Comment by Old-Second** [comment]
> I suggest that reinstalling this plugin can solve all the issues.

This doesn't work.

**Comment by Champion31415926** [comment]
> I suggest that reinstalling this plugin can solve all the issues.

really? i tried it but failed

r u sure there's no need to downloading the nailong folder to the project

**Comment by Refound-445** [comment]
按教程重走一遍，开个新的虚拟环境，nb bs的时候安装依赖选择Yes

**Comment by sp2dev** [comment]
去到插件文件夹然后手动删掉插件目录
```
rm -rf /path/to/yourbot/.venv/lib/python3.12/site-packages/nonebot_plugin_nailongremove*
```
然后重新安装即可
