### ISSUE TITLE
检测图片时出错 TypeError: Current driver does not support http client

### ISSUE THREAD

**Issue by StupidQu** [Refound-445/nonebot-plugin-nailongremove#33]
检测图片时出现错误：

```
12-24 15:46:21 [WARNING] nonebot_plugin_nailongremove | Failed to process Image(id='https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRvRc3iMfJLvTP-K6__nfX_KHK38RiYlwIg_woohPuK9_S_igMyBHByb2RQgL2jAVoQbx7Ld1tF83Mxw1xA3jUchQ&rkey=CAESKG0EIKe3_88rQZVWF884xt8Dvj9IWQ1xsarF8HlsPwNAspIS5m_hK2M', url='https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRvRc3iMfJLvTP-K6__nfX_KHK38RiYlwIg_woohPuK9_S_igMyBHByb2RQgL2jAVoQbx7Ld1tF83Mxw1xA3jUchQ&rkey=CAESKG0EIKe3_88rQZVWF884xt8Dvj9IWQ1xsarF8HlsPwNAspIS5m_hK2M', path=None, raw=None, mimetype=None, name='image.png'): TypeError: Current driver does not support http client
12-24 15:46:21 [DEBUG] nonebot_plugin_nailongremove | Stacktrace
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 673, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 640, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1992, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot_plugin_nailongremove\handler.py", line 96, in handle_function
    async for source, seg in iter_sources_in_message(msg):
> File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot_plugin_nailongremove\frame_source.py", line 187, in iter_sources_in_message
    yield await extract_source(seg), seg
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot_plugin_nailongremove\frame_source.py", line 179, in extract_source
    return await source_extractors[k](seg)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot_plugin_nailongremove\frame_source.py", line 154, in _
    image = await image_fetch(
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\tools.py", line 48, in image_fetch
    resp = await bot.adapter.request(req)
  File "C:\Users\Administrator\Documents\nb-gpt\.venv\Lib\site-packages\nonebot\internal\adapter\adapter.py", line 91, in request
    raise TypeError("Current driver does not support http client")
TypeError: Current driver does not support http client
```

系统是 Windows Server 2019，Python 3.12

**Comment by StupidQu** [comment]
按照 https://github.com/lgc-NB2Dev/YetAnotherPicSearch/issues/136 解决了
