### ISSUE TITLE
求助:无法处理图片

### ISSUE THREAD

**Issue by aptx4869102** [Refound-445/nonebot-plugin-nailongremove#34]
![image](https://github.com/user-attachments/assets/a647609d-24e8-4aa7-85f5-504d3d66990a)
如图,一直连接不上

**Comment by Refound-445** [comment]
请尝试科学上网

**Comment by aptx4869102** [comment]
代理一直有开

**Comment by aptx4869102** [comment]
![image](https://github.com/user-attachments/assets/56c691c0-d9f1-4a03-9dbd-74fbe72c9880)
补充:代理规则模式下,控制台信息ConnectError后面没有具体报错是空白
全局模式下为SSL的报错

**Comment by Refound-445** [comment]
请尝试其他代理，如仍然报错可进群询问

**Comment by Remik1r3n** [comment]
Same error here
同
Changing Proxy does not solve the problem
代理没用

**Comment by JohnRichard4096** [comment]
我在直接从qq的多媒体文件接口下载文件时也遇到了类似的问题，请禁用掉不安全的SSL版本，这可能会解决问题。

**Comment by JohnRichard4096** [comment]
可能的解决方案：在update.py:135处
```python
   def _download(self, tmp_path: Path, info: ModelInfo):
        httpx_progress_download(
            tmp_path,
            "GET",
            info.download_url,
            proxy=config.proxy,
            follow_redirects=True,
        )
```
在这个方法传入的参数内添加`verify=False`可能是一个解决方案。
总的代码如下：
```python
   def _download(self, tmp_path: Path, info: ModelInfo):
        httpx_progress_download(
            tmp_path,
            "GET",
            info.download_url,
            proxy=config.proxy,
            follow_redirects=True,
            verify=False,
        )
```

**Comment by JohnRichard4096** [comment]
此外，这与代理无关，腾讯的多媒体服务器位于国内，也不需要科学上网的多此一举。

**Comment by JohnRichard4096** [comment]
我提供的解决方案是错误的，我在一个使用该插件的机器人项目上通过堆栈信息找到了问题的根源（似乎）
<details><summary>展开查看日志</summary>

```log
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\remik1r3n\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\remik1r3n\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\remik1r3n\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\remik1r3n\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "c:\Users\remik1r3n\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\remik1r3n\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "f:\remibot3_1\bot.py", line 17, in <module>
    nonebot.run()
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "f:\remibot3_1\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "f:\remibot3_1\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 673, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 640, in run_forever
    self._run_once()
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 1992, in _run_once
    handle._run()
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 926, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 863, in simple_run
    await handler(
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "f:\remibot3_1\src\plugins\nonebot_plugin_nailongremove\handler.py", line 96, in handle_function
    async for source, seg in iter_sources_in_message(msg):
> File "f:\remibot3_1\src\plugins\nonebot_plugin_nailongremove\frame_source.py", line 195, in iter_sources_in_message
    yield await extract_source(seg), seg
  File "f:\remibot3_1\src\plugins\nonebot_plugin_nailongremove\frame_source.py", line 187, in extract_source
    return await source_extractors[k](seg)
  File "f:\remibot3_1\src\plugins\nonebot_plugin_nailongremove\frame_source.py", line 162, in _
    image = await image_fetch(
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\tools.py", line 48, in image_fetch
    resp = await bot.adapter.request(req)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\internal\adapter\adapter.py", line 92, in request
    return await self.driver.request(setup)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\drivers\httpx.py", line 134, in request
    return await session.request(setup)
  File "f:\remibot3_1\.venv\Lib\site-packages\nonebot\drivers\httpx.py", line 78, in request
    response = await self.client.request(
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "f:\remibot3_1\.venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)
```

</details>


其中，我注意到了

![Image](https://github.com/user-attachments/assets/e3cb5fbc-ca87-4cd2-92e0-2dab5c16b2a4)
在frame_source.py调用的来自alconna插件tools.py的` image_fetch`方法，第四十八行
```python
resp = await bot.adapter.request(req)
```
这个方法调用的方法又来自于Nonebot adapter基类，用于发起HTTP请求
```python
async def request(self, setup: Request) -> Response:
        """进行一个 HTTP 客户端请求"""
        if not isinstance(self.driver, HTTPClientMixin):
            raise TypeError("Current driver does not support http client")
        return await self.driver.request(setup)
```
在传入的Request类并没有提供有关SSL操作的选项，所以也就无法像httpx那样直接关闭验证，我只找出了问题，具体解决方案请开发者调整代码。

**Comment by Refound-445** [comment]
[/releases/tag/v2.3.6.post1](https://github.com/Refound-445/nonebot-plugin-nailongremove/releases/tag/v2.3.6.post1),fixed #34

**Comment by Refound-445** [comment]
已更新[releases/tag/v2.3.6.post1](https://github.com/Refound-445/nonebot-plugin-nailongremove/releases/tag/v2.3.6.post1)

**Comment by JohnRichard4096** [comment]
好耶



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年02月01日 15:38 |
| 收件人 | ***@***.***> |
| 抄送至 | John ***@***.***>***@***.***> |
| 主题 | Re: [Refound-445/nonebot-plugin-nailongremove] 求助:无法处理图片 (Issue #34) |

已更新releases/tag/v2.3.6.post1
